"use client";

import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layoutComponents/Navbar";
import Footer from "@/components/layoutComponents/Footer";
import useLenis from "@/hooks/useLenis";

// Load Montserrat from Google Fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const metadata = {
  title: "Spoontoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  useLenis();

  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-montserrat `}>
        <div className="w-full  min-h-screen h-auto flex flex-col">
          <Navbar />
          <main className="flex-grow">
            {children}
            {/* <FloatingButtons/> */}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
